### PR TITLE
fix(EG-680): minor updates to support NF integration

### PR DESCRIPTION
**Pull request by zigtan**
This PR fixes:

* S3Urls in the samplesheet for the uploaded files
* Sets the samplesheet S3Url for the `input` property
* Adds some missing imports for FE pages
* Renders the edited settings in Step 3. in the Step 4. summary page (to update to Nick's Figma designs still)
* Filters the Pipeline's sections for any that contain all hidden settings since it is not to be edited/visible in Step 3 and Step 4.

NOTE: There is still a bug with the manual editing of the input samplesheet text field in Step 3. This only gets updated and displayed properly in Step 4 after going back to Step 3, and then Step 4 again. It seems to be a storage update issue.

### CODE REVIEW

**Comment by simondib** [comment]
> Renders the edited settings in Step 3. in the Step 4. summary page (to update to Nick's Figma designs still)

The styling is a bit rough here but if you're comfortable merging as-is with a view to update to the hi-fi designs soon then it's all good.

> Filters the Pipeline's sections for any that contain all hidden settings since it is not to be edited/visible in Step 3 and Step 4.

This fix is already in `main` (although a different implementation, see: https://github.com/twobulls/easy-genomics/pull/311/files).

**Review by simondib — COMMENTED** [review]
Nice work all round - just a couple of comments to consider:

> Renders the edited settings in Step 3. in the Step 4. summary page (to update to Nick's Figma designs still)

The styling is a bit rough here but if you're comfortable merging as-is with a view to update to the hi-fi designs soon then it's all good.

> Filters the Pipeline's sections for any that contain all hidden settings since it is not to be edited/visible in Step 3 and Step 4.

This fix is already in `main` (although a different implementation, see: https://github.com/twobulls/easy-genomics/pull/311/files).

**Review by PurcyTwoBulls — APPROVED** [review]
LGTM

**Review by willholt-tb — APPROVED** [review]
lgtm

**Comment by zigtan** [comment]
Thanks everyone for the review. I'll update this branch with the latest main changes.

@simondib , yeah I think I'm comfortable with the roughness of the summary of the settings for now.

We can improve it to match the Figma design in a follow up ticket.

**Pull request merged**
